### ISSUE TITLE
Pre merge Signing Tool

### ISSUE THREAD

**Issue by Drawaes** [dotnet/corefxlab#1037]
This seems to be the only MS repo with this "check" that never finishes. There is auto CLA label already and this check never finishes so added noise. You can't see the PRs that are broken because they all are.

**Comment by benaadams** [comment]
What does it do?

**Comment by KrzysztofCwalina** [comment]
@joshfree would know

**Comment by ellismg** [comment]
The "check" waits for an MSFT engineer to assert that they have reviewed the SHAs that are going to be merged.  It has to be done manually and is usually done right before the PR is merged (since during review additional SHAs may be added or changed, due to history rewriting.

The tracking is part of some processes we are prototyping.  We started with this check in dotnet/buildtools and we're slowly rolling it out into other places.

I agree that the behavior around how the status checks are displayed on the PR page makes this a little confusing.  I'll file a bug about that and we'll see if we can do better (although it does mean probably moving away from the status API, which would be unfortunate for other reasons).

**Comment by Drawaes** [comment]
That's okay. If it is useful on your end I am okay with that. It's your trade off as to if you want to see PR's that are passing automated checks vs tracking that the complete process is followed.

**Comment by Drawaes** [comment]
This seems to have a purpose (internally for you) so I will close it.
