### ISSUE TITLE
PipelineConnection

### ISSUE THREAD

**Issue by grahamehorner** [dotnet/corefxlab#1043]
How/where can a developer find details about the underlying stream/connection; i.e. the client ip address for the network stream

**Comment by davidfowl** [comment]
You can't get it from the PipelineConnection, you need to know the concrete type of connection to see if that information is even available.

**Comment by grahamehorner** [comment]
@davidfowl how about adding a PipelineConnection PropertyBag to hold some information that relates to concrete type without the need to explicitly cast/use the concrete in the consuming code?

**Comment by davidfowl** [comment]
I'm not a fan of that. Casting seems like the better approach. Though you wouldn't need to cast because the callback for a connection should expose the concrete type (RioConnection/LibuvConnection/SocketConnection) with all of the appropriate properties. Nobody should have to revert to a property bag to dig out named properties (this isn't javascript 😄 ).

**Comment by Drawaes** [comment]
A simple solution, have anything that is a "socket" or "tcp" connection have another unrelated interface that has those properties. Eg ITcpConnection and have socket etc properties on there, otherwise you need to know if it is RIO, or Libuv etc. This wouldn't be a requirement and not directly related to Pipelines.

**Comment by davidfowl** [comment]
The moment you want to set a client specific setting you'll need access to the underlying handle which shouldn't be abstracted. If you want to set no delay, you'll have to call into libuv, or winsock or access the Socket object (if you're using SocketListener). I'm anti the abstraction until we fully understand why we need it and what would be on it.

That said I agree with @Drawaes , it's unrelated to pipelines.

**Comment by muratg** [comment]
Closing per @davidfowl's comment above.
