### ISSUE TITLE
[Question] Channels and TPL Dataflow Future

### ISSUE THREAD

**Issue by shaggygi** [dotnet/corefxlab#1126]
@stephentoub I finally took some time to read more about TPL Dataflow.  I watched one of [your related CH9 videos](https://channel9.msdn.com/Shows/Going+Deep/Stephen-Toub-Inside-TPL-Dataflow) and was very, very interesting.  I think it provides more for some projects I'm working on than Channels.

The [Channels ReadMe](https://github.com/dotnet/corefxlab/blob/master/src/System.Threading.Tasks.Channels/README.md) mentions it might be possible to integrate Channels into TPL Dataflow sometime after the API is moved to corefx.

My question is... is the plan to focus the integration soon after Channels API is moved to corefx or is this a backlog project further out (months/year)?  Understanding the usual (priorities, resources, etc.), I'm interested in hearing some of the thinking on newer capabilities/enhancements.  For example:

- What Channels offer being integrated into TPL Dataflow compared to TPL Dataflow today?
- Will Channels improve the TPL Dataflow allocation/performance that is being worked on in corefxlabs?
- If TPL Dataflow is used in projects today, will there be any major differences that would 1) break method calls, etc. and 2) be a big effort to modify code to utilize the integration changes?
- Other?

BTW... I hope Charles can stop by to interview you again at some point. 😄 👍

**Comment by omariom** [comment]
> I hope Charles can stop by to interview you again at some point. 

👍

**Comment by stephentoub** [comment]
> is the plan to focus the integration soon after Channels API is moved to corefx or is this a backlog project further out

Backlog, with the obvious caveat that if things are important to folks, changes can be suggested and implemented by the community.

> What Channels offer being integrated into TPL Dataflow compared to TPL Dataflow today?

Not sure I understand the question.  Are you asking what the value would be for integrating it?  Mainly just making it easier for code written with one to interact with code written for the other.  For example, you could link from a dataflow block to a channel, such that data from the dataflow block source flows to the channel... but such a thing would be easy to implement on top of the public API of TPL Dataflow, hence why I say "backlog".  I'm expecting that most integration here wouldn't save a whole lot and would really just be polish.

> Will Channels improve the TPL Dataflow allocation/performance that is being worked on in corefxlabs?

No more so that what could already be done internally in TPL Dataflow's implementation.  In other words, if it's possible to use channels as an internal implementation detail to improve TPL Dataflow's performance, then such changes could be done without channels as well.

> If TPL Dataflow is used in projects today, will there be any major differences that would 1) break method calls, etc. and 2) be a big effort to modify code to utilize the integration changes?

No, any changes that are made would need to be compatible with existing usage.

**Comment by shaggygi** [comment]
Thanks for the info @stephentoub.  I was mainly wondering what would be the benefits of integrating Channels with TDF that might not be as transparent (or at least from my understanding) in the ReadMe files.  After beginning to read more about TDF, I'm now seeing some of the overlap that others have been questioning.

I was a little confused thinking it was expected that Channels would be swapped with the interfaces under the TDF hood as it would cause breaking changes that utilized them.  While I like both, it does force a dev decision when to use one over the other.  In an ideal world, the Channels work would have been great to improve in TDF so the one API would offer the goodness of both.

I also wonder how and if one API is updated, would the other get similar features (related to buffering).  Take the [ignore issue I added recently](https://github.com/dotnet/corefxlab/issues/1127#issuecomment-272698427).  Would this be something to add to TDF (even if it does require a slightly different naming in the API)?

Thanks again for the info.  I'll close this issue in the near future.
