### ISSUE TITLE
SocketConnection: Available&EOF detection

### ISSUE THREAD

**Issue by tmds** [dotnet/corefxlab#1214]
@davidfowl System.IO.Pipelines.Networking.Sockets/SocketConnection has a comment
```
// we could do a zero-length receive, but this is not supported equally on all platforms (fine on Windows, but
// linux hates it). The key aim here is to make sure that we don't tie up an entire block from the memory pool
```

Do you have a small code repro that shows the difference between Windows and Linux?

**Comment by davidfowl** [comment]
It seems like this bug is fixed now so it might be worth reverting the code. Originally when @mgravell tested, zero byte reads to the socket API in .NET threw an exception which means bufferless reads weren't doable. It seems like it's since been fixed (and a test was added to corefx to asset that).

**Comment by stephentoub** [comment]
> It seems like this bug is fixed now 

We could never repro it on Linux.  We could repro on macOS, and it appeared to be an OS issue rather than a .NET issue.

**Comment by davidfowl** [comment]
Sure, I misspoke. Seems like "the issue" is no longer relevant 😄

**Comment by tmds** [comment]
@davidfowl feel free to close this or to keep it open as a reminder to revisit the code

**Comment by muratg** [comment]
Closing this one
