### ISSUE TITLE
Base64Encoder API requests

### ISSUE THREAD

**Issue by KrzysztofCwalina** [dotnet/corefxlab#1238]
- Add ComputeDecodedLength
- Consider changing the APIs to Try

**Comment by anurse** [comment]
Also, if any of the characters are invalid Base64 characters, one of two things happens:

1. If the character value is less than `123`, it is treated as a `0` value (this is really bad because it can result in silent failures)
2. If the character value is greater than or equal to `123`, an `IndexOutOfRangeException` is thrown. Likely due to the size of the decoding map: https://github.com/dotnet/corefxlab/blob/master/src/System.Binary.Base64/System/Binary/Base64.cs#L13

**Comment by ahsonkhan** [comment]
> 1. If the character value is less than `123`, it is treated as a `0` value (this is really bad because it can result in silent failures)

@anurse, I don't understand what this means. Can you clarify?

**Comment by ahsonkhan** [comment]
> Also, if any of the characters are invalid Base64 characters

This commit attempts to validate input and returns -1 if we receive ill-formed Base64 characters.
https://github.com/dotnet/corefxlab/pull/1562/commits/2aa27b38a1144eef78d54bf16a0b80b161b20f1f

**Comment by anurse** [comment]
> @anurse, I don't understand what this means. Can you clarify? Do you mean for any char value < 123, or some?

I was referring specifically to the behavior of **invalid** characters below `123`. The commit you referenced seems to cover that case.

**Comment by ahsonkhan** [comment]
Fixed in https://github.com/dotnet/corefxlab/pull/1562
