### ISSUE TITLE
GetAsciiString no longer throws for null characters

### ISSUE THREAD

**Issue by davidfowl** [dotnet/corefxlab#1271]
4 tests are failing in Kestrel when running against the latest corefxlab. These 4 strings used to throw when parsed into their individual parts and converted to ASCII using `GetAsciiString()` threw an InvalidOperationException. This no longer throws:

```
GET \0 HTTP/1.1\r\n
GET /\0 HTTP/1.1\r\n
GET /\0\0 HTTP/1.1\r\n
GET /%C8\0 HTTP/1.1\r\n
```

/cc @KrzysztofCwalina

**Comment by KrzysztofCwalina** [comment]
@davidfowl, is Kestrel doing URI validations anywhere? Ideally the check for 0 would be done there. The reason being:
1. URIs are allowed a subset of ASCII, i.e. 0 is the least of the problem; more ASCII chars need to be rejected.
2. 0 is a valid ASCII character
3. It's a valid input to System.Text.Encoding.ASCII.GetString(byte[])

**Comment by KrzysztofCwalina** [comment]
BTW, let me know if you prefer to fix this fast, and I will revert the check. I am just asking as I think it would be better to do proper check in one place.

**Comment by davidfowl** [comment]
I'll change kestrel to do this as part of scanning the path. Did you remove any other checks?

/cc @cesarbs

**Comment by davidfowl** [comment]
I'm going to make kestrel use the old version of the ascii encoding routine for now. That'll make sure there's no regression where we were depending on this logic.

**Comment by benaadams** [comment]
While it is valid ascii, Kestrel can't allow null terminating characters or high bits into the pipeline; whether in method, path, header name, header value etc

**Comment by davidfowl** [comment]
Closing this out

**Comment by KrzysztofCwalina** [comment]
no other checks removed. The routine validates that chars are from 0 to 127.

BTW, I added PrimitiveEncoder.DecodeAscii that might work better for Kestrel. It returns string.Empty for new byte[0], which is what Kestrel needs. All calls to GetAsciiString now check for null and then translate it to empty

**Comment by KrzysztofCwalina** [comment]
@benaadams, I agree. I am just saying there is more validation to do, so it might be better to do all of the validation (besides making sure it's ascii) in one place.

**Comment by benaadams** [comment]
Methods are scanned as to whether they [are valid tokens](https://github.com/aspnet/KestrelHttpServer/blob/dev/src/Microsoft.AspNetCore.Server.Kestrel/Internal/Http/KestrelHttpParser.cs#L544-L567) which is the limited range
Version can only be two strings
Path either under goes `> 0` && `<127` or is utf8 parsed (if contains `%`); otherwise can be anything
Header name value pairs are validated `> 0` && `<127`; otherwise can be anything

Null is a peculiarity due to potential of interpretation of nulls as premature terminators in strings by other downstream systems and cause buffer overruns. 1-126 shouldn't cause anything to break; >= 127 could hit a buggy encoding parser downstream.

Its more validation that things won't break rather than strict spec conformance (due to internet exposure). So path (non-escaped) and header name/values need to be checked for 1-127 - which is where the throwing ascii string creation is used.

For span its probably correct it doesn't throw for nulls as .NET doesn't have a problem with them; and in fact Redis clients use strings with the full 8 bit space for storing binary data (e.g. string or binary); which is why I mentioned 8-bit strings in the issue https://github.com/dotnet/corefxlab/issues/1269; where the check that its not 16-bit is more about inadvertent data loss than making a system misbehave.

**Comment by benaadams** [comment]
Also Encoding ASCII will replace > 127 with an alternative char rather than throwing by default which might be behaviour to consider for the more generic ascii decoder?

**Comment by benaadams** [comment]
However if the strings are pre-checked https://github.com/aspnet/KestrelHttpServer/pull/1447.... then it could just be a widen function with no checks? `Get8bitString`?

**Comment by KrzysztofCwalina** [comment]
As you said, Encoding.ASCII has a build in fallback. We opted for the fallback logic to be outside of the encoding functions. The function encode/decode as much as they can and then return how much they encoded/decoded. The calling code is then free to substitute the next coding units with whatever it wants and then continue. This is for the general purpose encoding/decoding routines that take input and output buffers. The routine that returns string does not have the fallback option.
