### ISSUE TITLE
Consider changing ReadableBuffer.First to a method

### ISSUE THREAD

**Issue by davidfowl** [dotnet/corefxlab#1285]
Now that its computed, it can be more expensive.

**Comment by ahsonkhan** [comment]
No longer relevant since we ReadOnlySequence already shipped. Closing.


https://github.com/dotnet/corefx/blob/8e53c7efea4efd28ba9d111dd4e70e3ca2f987f3/src/System.Memory/src/System/Buffers/ReadOnlySequence.cs#L55

https://github.com/dotnet/corefx/blob/8e53c7efea4efd28ba9d111dd4e70e3ca2f987f3/src/System.Memory/src/System/Buffers/ReadOnlySequence_helpers.cs#L84
