### ISSUE TITLE
Investigate why ReadOnlyBytes tests fail with System.InvalidProgramException

### ISSUE THREAD

**Issue by ahsonkhan** [dotnet/corefxlab#1419]
Example: https://github.com/dotnet/corefxlab/blob/master/tests/System.Buffers.Experimental.Tests/BytesReader.cs#L14
```C#
[Fact]
public void SingleSegmentBytesReader()
{
    ReadOnlyBytes bytes = Create("AB CD#EF&&");
    var reader = new BytesReader(bytes);

    var ab = reader.ReadBytesUntil((byte)' ');
    Assert.Equal("AB", ab.ToString(TextEncoder.Utf8));

    reader.Advance(1);
    var cd = reader.ReadBytesUntil((byte)'#');
    Assert.Equal("CD", cd.ToString(TextEncoder.Utf8));

    reader.Advance(1);
    var ef = reader.ReadBytesUntil(new byte[] { (byte)'&', (byte)'&' });
    Assert.Equal("EF", ef.ToString(TextEncoder.Utf8));

    reader.Advance(2);

    //Assert.True(reader.IsEmpty);
}
```

The sample test causes the error:
`System.InvalidProgramException : Common Language Runtime detected an invalid program.`

Why?

cc @KrzysztofCwalina

**Comment by shiftylogic** [comment]
The ToString extension method is passing a stack only structure to a StringBuilder function. Instead of converting the Utf8String to a string, it is boxing it by calling the "object" variant of Append. I changed the method to explicitly call ToString on the Utf8String instance and re-enabled the tests.

#1428
