### ISSUE TITLE
Should ReferenceCountedBuffer Begin Count at 1?

### ISSUE THREAD

**Issue by KodrAus** [dotnet/corefxlab#1531]
Hi all!

I understand this is still an active area so feel free to close if you're still working on this.

`ReferenceCountedBuffer` has an [`OnZeroReferences`](https://github.com/dotnet/corefxlab/blob/7ffb86952017f81f15ece74ffc7a52cd748248ba/src/System.Buffers.Primitives/System/Buffers/ReferenceCountedBuffer.cs#L32-L34) method that gets called whenever the ref count drops to zero.

Right now, this method could be called multiple times during the lifetime of an `OwnedBuffer`, if child `Buffer`s `Retain` and `Release` for short periods. So you can't rely on `OnZeroReferences` for disposal because it's likely you'll dispose the `OwnedBuffer` earlier than expected.

So what would an implementation do with `OnZeroReferences`? Release a pinned `GCHandle` maybe?

cc: @KrzysztofCwalina @mjp41

**Comment by i3arnon** [comment]
No sure, but If you were to pool these buffer instances this is probably where you would return them to the pool.

**Comment by davidfowl** [comment]
@i3arnon nailed it. That was the original intent but right now things are a bit up in the air WRT layering.

**Comment by KodrAus** [comment]
I'm not sure you could reliably do that though. For instance:

```csharp
// ref count: 0

using (var handle = buffer.Retain())
{
    // ref count: 1

    await DoSomethingAsync(buffer);
}

// ref count: 0. Buffer returned

using (var handle = buffer.Retain())
{
    // Buffer is returned, maybe even leased again. NO TOUCHING!
}
```

If you just `Retain` the `OwnedBuffer` and keep the ref count at least `1` until you're done with it why have a specific `OnZeroReferences` method when you can return the buffer on `Dispose` or `Release` explicitly from the owner?

**Comment by KodrAus** [comment]
I updated the issue title, because `OnZeroReferences` makes sense, but I think it's a bit of a loose cannon unless you include the `OwnedBuffer` in the retained reference count.

**Comment by KodrAus** [comment]
This is how I would expect `Buffer` to manage lifetimes wrt reference counting:
- `Buffer.Release` should not trigger `OnZeroReferences` unless the owned `ReferenceCountedBuffer` is released
- `ReferenceCountedBuffer.Release` should trigger `OnZeroReferences` once all retained `Buffer`s are released
- If you're doing synchronous work then there's no need to `Retain` the buffer. Calling `Release` or `Dispose` on the `ReferenceCountedBuffer` will do the same thing
- If you're doing asynchronous work, then you can `Retain` to extend the lifetime of the buffer. Calling  `ReferenceCountedBuffer.Release` during this op will trigger `OnZeroReferences` after the child `BufferHandle.Release`. Calling `ReferenceCountedBuffer.Dispose` invalidates retained `Buffer`s which means your lifetime logic is wrong

Is that correct or have I misunderstood the intentions?

**Comment by i3arnon** [comment]
This is how I gather `ReferenceCountedBuffer`s were meant to be used:
1. You take a buffer from the pool. (ref count = 0)
2. You retain it. (ref count = 1)
3. You copy some data onto it (e.g. an http request).
4. You pass it to some code to consume (e.g. `HandleReques`).
5. You release it (ref count = 0, `OnZeroReferences` is called and the buffer can return to the pool).

If for some reason inside `HandleRequest` you need to save that buffer before returning up the stack (e.g. fragmented payload) you retain it once more. That way step no' 5 would decrease the ref count to 1 instead of 0 keeping the buffer inside the `HandleRequest` code waiting to be released in the future (e.g. when all the other fragments arrive, or timeout).

If that's the case then:
- `Buffer.Release` should trigger `OnZeroReferences` because all references reference the `ReferenceCountedBuffer`
- `ReferenceCountedBuffer.Release` should trigger `OnZeroReferences` once the ref count reaches 0 meaning all references to the `ReferenceCountedBuffer` were released.
- You need to `Retain` and `Release` in synchronous work because that work might move the buffer reference to the heap to be consumed at a later time. You're not sure which part of your synchronous code will retain or release that buffer.

**Comment by KodrAus** [comment]
Thanks @i3arnon I like that model, I'm wondering who's responsible for that initial step 2 on the owned `ReferenceCountedBuffer`?
- If we say the lifetime of a `ReferenceCountedBuffer` is _as long as you have a `Retain`d reference to it_, then if you don't receive that `ReferenceCountedBuffer` from the pool in a retained state then as far as you know it's already gone!
- If we ensure that buffer is retained before letting users touch it then its lifetime is _at least until you explicitly call `Release` on the `ReferenceCountedBuffer` itself_.

So to protect yourself and callers from subtle use-after-free bugs, having a guard `Retain` on the `ReferenceCountedBuffer` sounds like a good thing to do. The question is who should do it?

- [`MemoryPool`](https://github.com/dotnet/corefxlab/blob/master/src/System.Buffers.Primitives/System/Internal/ManagedBufferPool.cs#L21-L24)
- [`ReferenceCountedBuffer`](https://github.com/dotnet/corefxlab/blob/master/src/System.Buffers.Primitives/System/Buffers/ReferenceCountedBuffer.cs#L13)
- Users the first time they see a `Buffer`

I'm just trying to think of ways to reduce potential edges in the API and provide some consistent guidelines for callers. Thanks for taking the time to chat about it :)

**Comment by KrzysztofCwalina** [comment]
@mjp41 is the expert on this.

**Comment by KodrAus** [comment]
@KrzysztofCwalina In #1591 you mentioned you played with starting the ref count for owned buffers at 1 but went back to 0, recommending callers wrap the owned buffer in a `using` block before passing to callers.

Was there some rationale behind this you can share? I've mostly come around to that idea, so long as buffers make an effort to protect themselves from use-after-free bugs, but I'm interested to know more.

**Comment by ahsonkhan** [comment]
Moved to [ReferenceCountedMemory](https://github.com/dotnet/corefxlab/blob/master/src/System.Buffers.Experimental/System/Buffers/Native/ReferenceCountedMemory.cs#L34-L36).
