### ISSUE TITLE
[Encoders] Possible SIMD optimizations for whitespace detection of code points

### ISSUE THREAD

**Issue by shiftylogic** [dotnet/corefxlab#1628]
* See EncodingHelper.cs :: IsWhiteSpace

**Comment by tannergooding** [comment]
This is another API that would benefit from https://github.com/dotnet/coreclr/issues/6906#issuecomment-307164495

**Comment by ahsonkhan** [comment]
https://github.com/dotnet/corefxlab/blob/89ea88c64f2dabe362c0a3df21d07313542c1d80/src/System.Text.Primitives/System/Text/Encoders/EncodingHelper.cs#L55

cc @GrabYourPitchforks - is this a good issue for the hackathon?

**Comment by GrabYourPitchforks** [comment]
I'm unsure as to the exact scenario under consideration here. Are you trying to find the first whitespace / non-whitespace character in a string (e.g., implementing `Trim`), or are you trying to speed up detecting whether a single character is whitespace (e.g., while enumerating)? The implementations will look slightly different in each case.

For example, consider the existing method `Char.IsWhiteSpace(char)`. This method is very inefficient due to the nature of how applications use it in practice. The overwhelming majority of characters we expect applications to throw at this method are ASCII non-whitespace. However, there are __five__ (!!) branches this method has to go through when faced with one of these characters as an input. A more optimized way of doing this would be to have an early-out to account for the majority of ASCII non-whitespace input:

```cs
if ((uint)(c - 0x21) <= (uint)(0x7E - 0x21)) {
    return NOT_WHITESPACE; // somewhere between '!' and '~', inclusive, no whitespace chars exist
} else {
    /* check for C0, space, and non-ASCII whitespace */
}
```

**Comment by ahsonkhan** [comment]
> Are you trying to find the first whitespace / non-whitespace character in a string (e.g., implementing `Trim`), or are you trying to speed up detecting whether a single character is whitespace (e.g., while enumerating)?

Looking at how we use this method, it seems like we use it for both scenarios:
Trim - https://github.com/dotnet/corefxlab/blob/b8e0ab345bca5c41f3640d88dd43562e0149b042/src/System.Text.Utf8String/System/Text/Utf8String.cs#L194
Is single character whitespace (but this looks very similar to Trim as well) - https://github.com/dotnet/corefxlab/blob/0687665071bb637f5bac78fc7c9f0f825b778dbd/src/System.Text.JsonLab/System/Text/Json/JsonParser.cs#L429

**Comment by GrabYourPitchforks** [comment]
TBH I don't expect to see real measurable perf gains from any vectorization at all. What would you even vectorize in this code path? And _in the common case_ would the overhead of setting up the vectorization logic be worth it, or is the common case to escape from the enumeration so early that a naive loop is best?

**Comment by ahsonkhan** [comment]
> or is the common case to escape from the enumeration so early that a naive loop is best

True. Given we didn't vectorize the span trimstart/trimend APIs for this reason, I believe the common case is that we find a non-white space early enough for vectorization to **not** be worth it.

**Comment by GrabYourPitchforks** [comment]
Upon further thought, maybe this is something meant for coreclr. There may be some merit to vectorizing methods like `String.Split`, but I don't think it would require changes to the methods under consideration in this particular issue.

**Comment by ahsonkhan** [comment]
Should we reverse `EncodingHelper.cs :: IsWhiteSpace` to be `IsNotWhiteSpace` which essentially does the following:
```cs
// somewhere between '!' and '~', inclusive, no whitespace chars exist
return ((uint)(c - 0x21) <= (uint)(0x7E - 0x21));
```
