### ISSUE TITLE
Make Decimal formatting non-allocating

### ISSUE THREAD

**Issue by KrzysztofCwalina** [dotnet/corefxlab#1765]
TryFormat(decimal ....) is implemented using CLR's ToString, which means it's allocating. 
At some point we should implement an non-allocating version.

**Comment by joshfree** [comment]
@AtsushiKan @shiftylogic

**Comment by stephentoub** [comment]
The plan for https://github.com/dotnet/corefx/issues/22403 is to add a non-allocating TryFormat methods.  That can be used instead of ToString.

**Comment by KrzysztofCwalina** [comment]
@stephentoub, we need to support UTF8 buffers.

**Comment by stephentoub** [comment]
> we need to support UTF8 buffers.

Sure, I'm not sure how my comment goes against that.

The PR added both UTF16 and UTF8 formatting.  For UTF16, the TryFormat method could be used to go directly into the caller-supplied output buffer; non-allocating.  For UTF8, the TryFormat method could be used to go into a stack-allocated `Span<char>`, since you know the longest a decimal can possibly be and it fits easily on the stack, and then convert that to the caller-supplied byte buffer; again, non-allocating (and no more conversion than is currently done in your PR).

This gets you to the goal of being non-allocating, which is what this issue is about, hence my comment.  If your goal is to format directly in UTF8 and skip UTF16, then yes, you'd need a custom implementation, but I have to imagine that if getting a UTF8 TryFormat for decimal to be non-allocating/non-extra-converting is lower priority (as mentioned in the PR), it'd be even lower priority to get one that's non-allocating but still does the conversion. :)

**Comment by KrzysztofCwalina** [comment]
@stephentoub, we also want to support existing versions of .net.

**Comment by stephentoub** [comment]
> we also want to support existing versions of .net.

In which case we can multi-target and the build against .NET Core can use the newer APIs.

**Comment by KrzysztofCwalina** [comment]
>In which case we can multi-target/cross-compile and the build against .NET Core can use the newer APIs.

What would it buy us? It would just make the packages more complicated (i.e. cross-compiled)

**Comment by stephentoub** [comment]
> What would it buy us?

The same thing it generally buys us: not having to re-implement the same functionality, or even if we choose to implement that functionality, getting the benefit of a non-allocating version until we do.  I'm not sure why this is controversial: this whole thread started because you said it's allocating due to using ToString, and all I suggested was being able to use TryFormat instead once it's there.

**Comment by KrzysztofCwalina** [comment]
> I'm not sure why this is controversial: this whole thread started because you said it's allocating due to using ToString, and all I suggested was being able to use TryFormat instead once it's there.

It's controversial because: a) today the package is not-cross compiled, i.e. simple. b) decimal is really here for completeness, i.e. I kind of don't care too much that it's allocating. Note that the rest of the parser are non-allocating already.

**Comment by jkotas** [comment]
>  today the package is not-cross compile

Right, this is the case today but it is unlikely to be the case once it moves to corefx. All similar packages got cross-compiled very quickly as soon as they are moved to corefx. This one is not going to be exception - folks will want to make it run better on .NET Core using constructs that are available in .NET Core only.

Also, I do not think we will want to have the optimized parsing routines duplicated in .NET Core. We will want to use the same optimized core of parsing, formatting and encoding routines for both existing classic methods and these new methods. It means that this code is very likely going to live in .CoreLib on .NET Core once we are done.

**Comment by KrzysztofCwalina** [comment]
I think this is done.
