### ISSUE TITLE
Support optional offset from UTC in Date and Time types to align with XSD

### ISSUE THREAD

**Issue by mattjohnsonpint** [dotnet/corefxlab#1901]
@mconnew and I met yesterday to discuss some of the feedback from #1740, and came to a consensus on the following: 

- [`xs:date`](https://www.w3.org/TR/xmlschema11-2/#date) and [`xs:time`](https://www.w3.org/TR/xmlschema11-2/#time) require supporting an optional offset from UTC.
- Though this is an edge case, it is valid by spec and can appear in customer data.
- We cannot truncate or otherwise ignore the offset, as it would lead to data loss in those cases.
- We do want `System.Date` and `System.Time` to be the primitives used to serialize/deserialize this data.
- Creating separate types for "when offset exists" vs. "when offset doesn't exist" is problematic, and doesn't cover the majority case.
- Therefore, we must also support an optional offset in these types.

The offset should be exposed as a `TimeSpan?` (nullable) type as a getter-only property, and as a `TimeSpan` in overloads to the constructors.  It will also need to be taken into consideration during all methods, especially parsing, formatting, and those methods that interact with other types.

This will create some scenarios that can only result in exceptions.  For example:

```csharp
Date d = Date.Parse("2017-11-03Z");     // valid
Time t = Time.Parse("12:00:00-07:00");  // valid
DateTime = d.At(t);                     // must throw, because offset mismatch
```

These edge scenarios are acceptable, and should be documented as such.

**Comment by mj1856** [comment]
Some precedent:
- [SQL Server 2014](https://msdn.microsoft.com/en-us/library/ee240708(v=sql.120).aspx) (regarding typed XML data only):
  > *The storage format in SQL Server 2014 for types xs:dateTime, xs:date, and xs:time has been changed to support values with or without time zone information and to allow for preservation of the time zone.*

- [Example from 2011 of how customers have been working around the lack of support for this feature](https://www.codeproject.com/Articles/182960/WCF-Support-for-xs-date).  Particularly:
  > *Date type is very useful. It exists in most databases including SQL Server and in many frameworks and languages (although not all). Our life would be easier if Microsoft supported it in WCF and in the .NET Framework natively.*

(lots of others... just thought I'd link a couple)

**Comment by mj1856** [comment]
I started implementing this, and have come across what I think is a showstopper.

```csharp
Date d1 = Date.Parse("2018-01-01");  // d1.Offset must be null
Date d2 = Date.Today;                // d2.Offset must be set, using the local time zone
if (d1 > d2)                         // ???
```

Basically, the [`Compare`](https://github.com/dotnet/corefxlab/blob/061e877eaf5e49d14b7407269e464f39906daccc/src/System.Time/System/Date.cs#L666) implementation must now consider both day number and offset, but offset is not always present.

I don't believe the guidelines would support throwing an exception during comparisons of objects of the same type.  Even if they did, the case here would be extremely common and there wouldn't be any clean workaround.

Thoughts?

**Comment by mconnew** [comment]
The offset only has meaning when combined with a time. Let's take the real world analog that you previously mentioned, that a date represents a square on a calendar. If you had two physical calendars, one located in Washington, and the other located in New York and you were asked to compare the squares which represents Jan 1 2018 on those two calendars, you would say they are for the same date. If you were to try and arrange a mutual time to have a phone call, then the offset matters, but when choosing the day, it doesn't matter. So I would say the Compare should say they are the same, and Equals should say they are different as Compare is about ordering items and Equals is about equivalence.

**Comment by YohDeadfall** [comment]
There is nothing directly said about comparison (`<`, `<=`, `>`, `>=`) in the guidelines, but equality operators and the `Equals` method must not throw exceptions. It's [CA1065: Do not raise exceptions in unexpected locations](https://msdn.microsoft.com/en-us/library/bb386039.aspx). And because all comparisons are unexpected locations, you can't throw exceptions there.

Probably you can use rules from [XML Schema Part 2: Order relation on dateTime](http://www.w3.org/TR/xmlschema-2/#dateTime-order).

**Comment by mj1856** [comment]
> So I would say the Compare should say they are the same, and Equals should say they are different...

Really?

```csharp
a.CompareTo(b) == 0
a,Equals(b) == false
```

I cannot fathom how such a thing could be reasonable.  Do you have any other examples of commonly used objects in .NET that behave this way?

WRT the analogy, keep in mind that XML Schema describes the offset of an `xs:date` to apply specifically to the first instant of the date, which is usually (but not always) `00:00`.


@YohDeadfall - Thanks for the link to the ordering in XML Schema.  That is indeed relevant, however I find it incomplete for this purpose.  Cases C and D describe the problem well, but stop with inequality at step 3, stating nothing about equality.  The implied step 4 is "otherwise the result is indeterminate."

`Compare` can only return values -1, 0, or 1, indicating `<`, `=`, or `>`.  There is no result that indicates `<>`, nor is there a way to indicate indeterminism.

**Comment by mj1856** [comment]
The more I think about this, the more I think it's asking for trouble to support offsets on these types.  It really is an SRP violation in the same way that `DateTimeKind` is - which was a mistake IMHO.  I don't want to repeat the same mistakes here.  I'm leaning back toward closing this out as something not to be done - even if it means we don't map to `xs:date` and `xs:time`.

FWIW, I made the case for NodaTime to include support for such data, which are coming in new types called `OffsetDate` and `OffsetTime`.  (These are being including in the upcoming 2.3.0 release, which you can get as prerelease beta on Nuget now.)  In the NodaTime world, separate types for separate concerns are part of the design philosophy so it makes sense to build them like this.  I don't see that being possible for .NET though.  The whole purpose of building these minimal `Date` and `Time` types is to take a bare-minimum approach to filling in the gaps of the existing type system.  I envision the release notes will provide guidance that if one needs a more complete type system then to use a third-party library like Noda Time.

That said, while Noda Time implements `IXMLSerializable` on all types, it doesn't attempt to provide an XML Schema (with `XmlSchemaProviderAttribute` or otherwise) for any of them.  One assumes you'd have to train the serializer to do this (though I'm not sure exactly the mechanism for that).

**Comment by Kukkimonsuta** [comment]
I might be completely off here, but could we just include `TimeSpan Offset` property but completely ignore it otherwise? It would allow mapping to `xs:date` and `xs:time` and developer could react to these, but in comparison and equality it would be ignored because it would be just "metadata" that carries along with the instance. This wouldn't match comparison behavior defined in xml schema, however it would match the existing behavior of `DateTime.Kind`. In my book both `Date` and `Time` don't represent an instant, but instead logical date and time - like information that on 24.12.2018 a world wide chain store will be closed, but on 31.12.2018 it will be open from 8:00 to 15:00 - it really doesn't matter where in the world the store is - the same purpose for which you'd rather use `DateTime` over `DateTimeOffset`.

**Comment by jzabroski** [comment]
> The more I think about this, the more I think it's asking for trouble to support offsets on these types. It really is an SRP violation in the same way that DateTimeKind is - which was a mistake IMHO. I don't want to repeat the same mistakes here. I'm leaning back toward closing this out as something not to be done - even if it means we don't map to xs:date and xs:time.

Agreed!!!!!!!

**Comment by jzabroski** [comment]
> I I might be completely off here, but could we just include TimeSpan Offset property but completely ignore it otherwise? It would allow mapping to xs:date and xs:time and developer could react to these, but in comparison and equality it would be ignored because it would be just "metadata" that carries along with the instance. This wouldn't match comparison behavior defined in xml schema, however it would match the existing behavior of DateTime.Kind

@Kukkimonsuta
You ARE completely wrong :-)
The problem we ordinary developers face is computer scientists try to develop an API by addressing edge cases in an algorithmic completeness sense rather than domain driven design (DDD) sense.

It looks like @mj1856 is coming around to DDD by mentioning Single Responsibility Principle (SRP) violation of DateTime having DateTimeKind. By allowing DateTime to represent both a floating time as in "Fox TV News at 6pm" airing at 6pm in each respective time zone in the US, but also airing at a distinct point in time, it conflates two responsibilities and makes exchanging data between third party libraries harder.

In my opinion, first rewrite the API ,then provide mapping to xsd.
