### ISSUE TITLE
Productize NativeOwnedMemory

### ISSUE THREAD

**Issue by KrzysztofCwalina** [dotnet/corefxlab#1924]
```c#
namespace System.Buffers
{
    public sealed class NativeOwnedMemory<T> : OwnedMemory<T>
    {
        public NativeOwnedMemory(void* pointer, int length);
        ...
    }
}
```

**Comment by KrzysztofCwalina** [comment]
cc: @stephentoub

**Comment by mgravell** [comment]
I agree this is a desirable use-case to consider and implement in the library - I've had to implement it a few times (see https://github.com/dotnet/corefx/issues/26781), as has @Drawaes (apparently). In particular, there are nuances around reserving the buffer that would be well worth implementing correctly once, rather than letting folks mess it up.

This is quite different to the existing `NativeOwnedMemory`, though, which is a non-generic  `OwnedMemory<byte>` and which handles the lifetime *internally*.

**Comment by Drawaes** [comment]
Yes I have implemented this for memory mapped files and I have implemented it for non pageable memory as well, pretty much the same both times so a general purpose one would be great.

**Comment by stephentoub** [comment]
> This is quite different to the existing NativeOwnedMemory

That's just a test implementation that sufficed for what was needed in the tests.

**Comment by joshfree** [comment]
Migrated to https://github.com/dotnet/corefx/issues/28283
