### ISSUE TITLE
Unable to load DLL 'brotlienc.dll'

### ISSUE THREAD

**Issue by jmkni** [dotnet/corefxlab#1958]
Hi all

I am using Asp.Net Core 2.0.3 and have followed the instructions here - https://www.meziantou.net/2017/07/17/use-brotli-compression-with-asp-net-core

When I actually try to use the provider, I get an exception saying the DLL can't be found, as shown below:

![brotlierror](https://user-images.githubusercontent.com/6376610/33370993-3587d464-d4f1-11e7-93bf-e4aa644effa0.PNG)

Might the instructions in the link be out of data? I'm wondering if there is maybe an extra step I need to go though?

Regards

**Comment by ahsonkhan** [comment]
@ianhays, do you know how to resolve this issue?

**Comment by ianhays** [comment]
Unfortunately that error message is one that has plagued me in the past and is entirely unhelpful for actually diagnosing the error.

There a couple of issues that could cause it:
- The brotlienc dll didn't restore properly and isn't in the folder where it should be
- The brotlienc dll was restored but the architecture is incorrect (e.g. x86 instead of x64) so loading failed
- The brotlienc dll restored the correct version, but put it in a different folder
- permissions issues

The best way to start figuring out what's wrong is to check you bin/packages folders for the missing dll. If it's in both places, check the architecture for which it was built. If that's also valid, check that you have access to it.

**Comment by jmkni** [comment]
Thanks @ianhays , will give it another go later and let you know!

Not urgent at all, would just be interesting to see it working. Currently delivering an Angular app, which comes down at about 450KB GZipped, keen to see what Brotli brings it down to!

**Comment by BravoTango86** [comment]
Adding BrotliNative fixed this for me.

**Comment by kasper3** [comment]
@ianhays tested with nuget 4.4.1 in powershell

```powershell
nuget install System.IO.Compression.Brotli `
  -source https://dotnet.myget.org/F/dotnet-corefxlab/api/v3/index.json `
  -source https://dotnet.myget.org/F/dotnet-core/api/v3/index.json `
  -output deps `
  -Prerelease

ls -r deps/**/*brotlienc*
```

no results.

Per @BravoTango86's comment, additional package BrotliNative is required (substitute `System.IO.Compression.Brotli` with `BrotliNative` in `nuget install` command) to make `brotlienc.dll` restored. Seems like this should be treated as a packaging bug?
