### ISSUE TITLE
BufferReader API : Add TrySkip (System.Buffers.Primitives)

### ISSUE THREAD

**Issue by mgravell** [dotnet/corefxlab#2020]
Functionally similar to `Skip`, but for EOF scenarios instead of raising `ArgmentOutOfRangeException`, it would simply return `false`. All other aspects remain identical, including the side-effects and final state of the reader for both success and failure.

Calling with a negative `length` would still `throw` - this is simply for the EOF case, not the brain-dead case.

Justification: consumers often need to use skip - it is why it is there; equally, consumers often need to respond to EOF scenarios. Currently, we can `catch`, but to do that *granularly* has performance implications (and incorrectly catches the -ve `length` scenario); and to do it too *widely* risks mis-identifying categories of errors as false-positives (`ArgumentOutOfRangeException` is pretty common).

With `TrySkip`, we could check at exactly the right level, without even falling into the -ve `length` trap.

This cannot be added as an extension method, as it requires access to the underlying primitives.

Implementation suggestion: make `TrySkip` the primary:

```
    public bool TrySkip(int length) {...)
    public void Skip(int length) {
        // this whitespace and lack of braces intentional to cause David apoplexy
        if(!TrySkip(length))
            ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument.length);
    }
```

Note this also touches on #2019
  
  ---

Edit: possible alternative API: have `TrySkip` return either the number of bytes successfully skipped, or the number of bytes that are still outstanding (the second sounds odd, but is likely to be the number people care about most - if they're skipping data, they want to know how much more they need to fetch and skip):

```
    public int TrySkip(int length) {...}
    public void Skip(int length) {
        // this whitespace and lack of braces intentional to cause David apoplexy
        if(TrySkip(length) != 0)
            ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument.length);
    }
```

In addition to "the number still remaining" being the number people will want (and need to calculate) - rathen than "the number skipped", this also has the *very slight* advantage that all the subsequent `if` tests become `brtrue[.s]` / `brfalse[.s]` rather than `ldloc[.s] {numberWeWantedToSkip}`, `beq[.s]` / `bne.un[.s]`

**Comment by pakrym** [comment]
I like `int TrySkip` more but not sure about returning amount of bytes left, it's a bit unusual.

**Comment by mgravell** [comment]
I'll take what I can get. If that's the sticking point: return whichever
you like :)

**Comment by knocte** [comment]
> but for EOF scenarios instead of raising ArgumentOutOfRangeException

Sorry for the intromission in this issue, but it might be related (and since this is the only issue in this repo that mentions ArgumentOutOfRangeException...).

I have some code System.IO.Pipelines-based code which when using System.Buffers, it normally works, but under special circumstances (debugging in an Android phone, maybe slower, thus racy code?) I get the aforementioned ArgumentOutOfRangeException in this call to System.Buffers.BuffersExtensions.PositionOf():
https://gitlab.com/DiginexGlobal/geewallet/blob/master/src/GWallet.Backend/JsonRpcSharp.fs#L52

Not entirely sure if TrySkip would help in my scenario, or if my code is racy or not EOF aware (the latter I doubt cause it works when not debugging...). Full stack trace is here: https://gitlab.com/DiginexGlobal/geewallet/issues/23

(If I try to avoid the call to PositionOf in this case by checking buffer.IsEmpty first, surprisingly enough I get a NullReferenceException, even if ReadOnlySegment&lt;byte&gt; is a struct...) Thanks

**Comment by ahsonkhan** [comment]
@knocte, can you please file an issue related to your scenario in corefx (label System.Memory)?
https://github.com/dotnet/corefx/issues?utf8=%E2%9C%93&q=is%3Aopen+is%3Aissue+label%3Aarea-System.Memory

That is where the implementation of this API lives: https://github.com/dotnet/corefx/blob/9d3bce9a53234a98e25513909a843a277f9b33da/src/System.Memory/src/System/Buffers/BuffersExtensions.cs#L18

**Comment by knocte** [comment]
>@knocte, can you please file an issue 
Sure done: https://github.com/dotnet/corefx/issues/32711 but I don't think I have permissions myself to add labels. Cheers
