### ISSUE TITLE
Investigate moving the JsonWriter "pretty print" feature to a post-processing step

### ISSUE THREAD

**Issue by ahsonkhan** [dotnet/corefxlab#2295]
For context: https://github.com/dotnet/corefxlab/pull/2292#issuecomment-389549705

Investigate if we can optimize the JsonWriter by formatting the output at the end, rather than during each Write call.

cc @Tornhoof, @KrzysztofCwalina

**Comment by Tornhoof** [comment]
I have to admit, I did not think about much streaming. Assuming that streaming will be done via Pipes (ex-Channels) (even though I don't know how those work with chars), I thought a PPP (Pretty Printer Pipe) would  work, that one wraps the normal i/o pipe and does the post processing work. But I only have very limited experience with pipes, all my current streaming experiments are several times slower than the fully buffered ones. On the other hand, maybe the integrated approach works fine for you, in SpanJson even having the code path in there made everything slower by 10% (mainly due to additional code size and inlining issues).
