### ISSUE TITLE
[Question] Separate Enums and Class to Different Files

### ISSUE THREAD

**Issue by shaggygi** [dotnet/corefxlab#2386]
Would it be appropriate to separate enums and class to their own code files or is the standard for this repo okay with grouping?  I can create a PR if it is better to separate.  Let me know.

For example, [Pin.cs](corefxlab/src/System.Devices.Gpio/System.Devices.Gpio/Pin.cs) includes PinMode, PinValue, Pin, etc.

**Comment by ahsonkhan** [comment]
Generally speaking, we try to separate enums and classes to their own files. However, we don't follow that guidelines too strictly. PRs are definitely welcome :)

cc @edgardozoppi

**Comment by edgardozoppi** [comment]
I was planning to do it later since I wanted to concentrate in more important things first. :)
@shaggygi I appreciate your comment but I think there is no need for you to spend time in creating a PR for this, I will take care of it soon. The reason is I am still making lots of changes to the project and moving code between files at this point will create several git conflicts that I would like to avoid if possible. Thanks!

**Comment by edgardozoppi** [comment]
This change is included in PR #2400.
