### ISSUE TITLE
StringSegment API

### ISSUE THREAD

**Issue by davidfowl** [dotnet/corefxlab#245]
We have this internal API that we use to parse header values (narrow use today), but could be more generally useful. It's very related to Span<T> where T is char in this case.

https://github.com/aspnet/HttpAbstractions/blob/davidfowl/parsing-hepers/src/Microsoft.AspNet.Http.Extensions/Internal/StringSegment.cs

Related classes:

https://github.com/aspnet/HttpAbstractions/blob/davidfowl/parsing-hepers/src/Microsoft.AspNet.Http.Extensions/Internal/

Thought it would be interesting to look at.

/cc @KrzysztofCwalina

**Comment by davidfowl** [comment]
@KrzysztofCwalina One thing I think would help for non allocating parsing:

- A first class StringSegment 
- Primitive parsers that took string segments
- Substring operations on String (or extension methods) that returned a StringSegment
- A String.Split operation that returned a struct based enumerator over the pieces

**Comment by KrzysztofCwalina** [comment]
cc @ellismg, @krwq
Yup, this is definitely something we want to do. But again, the best way to do it is with Span<char>. Today, we could do something less efficient, but it would be a lot of work and will be thrown away after we have Span based solution.

**Comment by krwq** [comment]
Utf8String is technically a segment right now. In order to get a copy you need to call one of the copy functions

**Comment by davidfowl** [comment]
Soo we wait until we get span to do allocation free substrings and split and other commonly used string utilities?

**Comment by davidfowl** [comment]
What about Int32.TryParse(string, int, offset) style API

**Comment by KrzysztofCwalina** [comment]
Substrings and split will have to wait for slices. I can imagine adding TryParse methods like that sooner. @Petermarcu @piotrpMSFT, any thoughts on funding?

**Comment by krwq** [comment]
@davidfowl I like the idea, I think the best way to figure out the best design would be to take one of our implementations which could potentially use it and start converting it and see if it's failing over or is annoying to use and fix accordingly.

I wonder what kind of scope should we include - i.e. should this rather look like raw static functions or rather some clever (clever="equally fast" in this case) way of abstracting it so that we can support different types of numbers (i.e. something I can easily replace standard numbers with roman numbers or linguistical representation) or perhaps both but start with a simple thing and then build on top of it..
@KrzysztofCwalina - we are open source, this is experimental repo - let's come up with clear goals what are we trying to achieve and let help people build this and go wild - perhaps there is already existing open source implementation we could use i.e. some code from C++ compiler which we could simply port over here. I think it's ok to make design errors as long as we can fix them and do breaking changes, if we start locking down on things then we can accidentally lock the immature design and start fixing it by creating tons of abstraction

**Comment by davkean** [comment]
We should close this one in lieu of https://github.com/dotnet/corefx/issues/20378.
