### ISSUE TITLE
Span<T> should be stack only

### ISSUE THREAD

**Issue by KrzysztofCwalina** [dotnet/corefxlab#257]
This is the leading proposal + Roslyn analyzer to detect when Span is stored on the heap. FYI: it cannot be stored on the heap beacause of struct tearing issues. Also, stack only spans will make it easier to return buffers to the pool. When stack pops to the frame that rented/allocated the buffer, we know that no outstanding pointers to the buffer exist, except for BoxedSpans, which will be ref counted.

[StackOnly]
public struct Span<T>
{
..
    public static implicit operator Span<T>(T[] array);
    public BoxedSpan<T> Box();
}

public sealed class BoxedSpan<T>
{
    public static implicit operator Span<T>(BoxedSpan<T> span);
}

**Comment by CodesInChaos** [comment]
> When stack pops to the frame that rented/allocated the buffer, we know that no outstanding pointers to the buffer exist, except for BoxedSpans, which will be ref counted.

What about returning a span from that function or passing it outwards via a `ref`/`out` parameter?

----

What's a bit annoying about making these stack-only is that local variables can be allocated on the heap (e.g. closures and `async` methods), preventing the use of spans in those cases. But I guess that's an acceptable price to pay for getting a safe high performance slice type.

In principle it should be possible to safely use slices stored on the heap, as long as they're not written to after the object containing them escapes to other threads.

----

Concerning the boxed span, you should consider adding a generic `Box<T>` to the framework for type safe boxing, instead of implementing a special case solution for `Span`.

**Comment by KrzysztofCwalina** [comment]
This will be enforced by the language
