### ISSUE TITLE
Consider adding dictionary type optimized for very small 'n'

### ISSUE THREAD

**Issue by rynowak** [dotnet/corefxlab#2652]
Inspired by seeing: https://github.com/dotnet/coreclr/pull/8216

We've come across many cases in ASP.NET where we want to expose something like the `IDictionary<,>` contract, but we know that the number of items used with it will always be a small number (N < 10). In some cases, potentially hundreds of these may be created for a single request, and so we want them to be pretty slim. 

We've created a few specialized types of our own to meet this need, but the canonical case is something like [AttributeDictionary](https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.ViewFeatures/ViewFeatures/AttributeDictionary.cs). There's a ton of boilerplate associated with implementing `IDictionary<,>` and so we're not thrilled with implementing one of these each time we want to optimize something. We're also not necessarily married to `IDictionary<,>` as the primary contract. That's what there is, so that's what we're using to avoid reinventing the wheel (while reimplementing the wheel).

In general we care about get/set values and enumeration in particular being fast for a small number of items.

**Comment by danmosemsft** [comment]
As an aside, it is possible to make a List that is smaller than real List at first. [Eg.,](https://github.com/Microsoft/msbuild/blob/e70a3159d64f9ed6ec3b60253ef863fa883a99b1/src/Build/Collections/MultiDictionary.cs#L165)

**Comment by omariom** [comment]
Interesting approach.
 It is WPF repo 
https://github.com/dotnet/wpf/blob/master/src/Microsoft.DotNet.Wpf/src/Shared/MS/Utility/FrugalMap.cs

**Comment by ygoe** [comment]
I'm also looking for a slim Dictionary type for my current task. The experimental type mentioned above doesn't work for me, in fact it doesn't even seem to be a dictionary. I can't add items to it, only get. Continuing to look for another solution.

I have hundreds of thousands (will become millions in the end) of small "documents" (key value pairs) and keep them in memory. With a traditional dictionary, I clearly see a memory increase from 155 to 205 MB when the document dictionaries pass the prime length of 7, if even just by 1. The contained data is already pooled so that doesn't have much of an effect.

**Comment by ygoe** [comment]
A quick update: I really quickly cobbled together a class implementing `IDictionary<string, object>`, internally using a simple `List<Entry>` where `Entry` is a private struct containing a `string Key` and a `object Value`. Instead of hashing, keys are searched in the list of entries (`for` instead of `foreach` and `object.Equals` for the keys). This has decreased my memory usage from 208 to 124 MB and a simple query over all data (with some grouping) took just 50 instead of 70 milliseconds. Using an `Entry[]` array instead of the `List` even brought me down to 109 MB. I guess my problem is solved. For small data, hashing may not be required and linear searching is even better.
