### ISSUE TITLE
How about making release tag on every important merge or milestone

### ISSUE THREAD

**Issue by buybackoff** [dotnet/corefxlab#2691]
I do really want to follow what's preparing next for `corefx`, but physically cannot follow every notification (usually just miss important ones among others). This repo has zero releases. And since this is a "lab" repo, releases could be quite arbitrary for any important change, just make it a `date` or `counter+1`. E.g. when you merged finally `DictionarySlim` or Json stuff, it would be so nice to see it as "almost ready", but not every line change. And GitHub has "watch releases" mode that is perfect for that.

**Comment by ahsonkhan** [comment]
Since this repo has zero releases (like you mentioned), I am not sure if it makes sense to make such guarantees to avoid adding overhead/expectations which this repo doesn't adhere to. What you should be watching is check-ins/announcements/releases in corefx itself since that is where "ship-ready"/"productized" code lives.

Some of the projects within corefxlab may never reach that stage which and could easily be prototypes that give us the ability to experiment and learn, along with gather feedback from those like you who are uniquely interested in the early stages.

> And since this is a "lab" repo, releases could be quite arbitrary for any important change

That seems like an oxymoron ;)
There should be no "important" changes in a repo like this.

When we did merge Json stuff, it went through API review, announcement, blogs, videos, etc., **and all of which was within corefx.** The same would happen to other projects once (and if) they reach that stage.

**Comment by buybackoff** [comment]
> There should be no "important" changes in a repo like this.

I meant interesting/important ones. 

What I meant is that GH blue dot is like email inbox. Many times I had to unsubscribe from some hot discussion here to avoid distraction.

That was just an idea, not an issue, so closing it. But there should a middle ground between release blog posts and every commit/issue here.
