### ISSUE TITLE
Why a columnIndex is required for Insert method

### ISSUE THREAD

**Issue by xcaptain** [dotnet/corefxlab#2798]
https://github.com/dotnet/corefxlab/blob/154fafa095dd6159867c4aeb096d31c60ae96ad0/tests/Microsoft.Data.Analysis.Tests/DataFrameTests.cs#L26-L28

I tried

```C#
dataFrame.Columns.Insert(1, dataFrameColumn1);
dataFrame.Columns.Insert(3, dataFrameColumn2);
```

but the tests failed. Is this `columnIndex` really needed? I think a `columnName` is to index a column in a dataframe.

**Comment by pgovind** [comment]
Hey @xcaptain, I assume you already got past this?

**Comment by xcaptain** [comment]
@pgovind Thanks, I have already figured out this problem. Now I have a second question, I found in https://github.com/dotnet/corefxlab/blob/master/src/Microsoft.Data.Analysis/DataFrame.cs#L59 the return type is object, is it possible to use a strong type?

I'm interested in dataframe implementations, I found an interesting paper http://okmij.org/ftp/Haskell/HList-ext.pdf, I'm still reading it, don't know if the idea can be used in this project

**Comment by pgovind** [comment]
Do you know the type of your column? If it is a `PrimitiveDataFrameColumn` you can cast `df.Columns[columnIndex]` to a `PrimitiveDataFrameColumn` and use this: https://github.com/dotnet/corefxlab/blob/master/src/Microsoft.Data.Analysis/PrimitiveDataFrameColumn.cs#L205. `StringDataFrameColumn` has similar API. Unfortunately, because `DataFrame` is a loosely typed structure, we lose type information on most of the returned types. I'll have a look at the paper you linked to in a bit.
