### ISSUE TITLE
DataFrame.Sample doesn't check for already generated indices

### ISSUE THREAD

**Issue by zHaytam** [dotnet/corefxlab#2806]
Hello,

The `Sample` method in `DataFrame` (code [here](https://github.com/dotnet/corefxlab/blob/master/src/Microsoft.Data.Analysis/DataFrame.cs#L325)) does not check if an index was already generated by `rand`. Most of the time I get duplicate rows because of it.

**Comment by pgovind** [comment]
Indeed. We should fix this for the next preview

**Comment by RamonWill** [comment]
Hi @pgovind ,

I have looked into this issue and came up with a solution using the Fisher-Yates Shuffle Algorithm, which would resolve this issue in O(n) time complexity. I have also included a test for this and it passes all existing tests.

As this DataFrame doesn't has an index like the Pandas DataFrame for Python, I would create an array of all numbers (representing each row) from range 0 to Rows.Count or Int32.MaxValue.

I would then shuffle this array inplace using the algorithm and then for loop through the beginning of the now shuffled array to the numberOfRows and assign the shuffled values to the indices variable. This solution is better than using a HashSet because the shuffled array will already consist of unique indices and the shuffle itself is inplace. This would also avoid having to nest a do while loop inside of a for loop to generate the next random number if it has already been seen.

```
       public DataFrame Sample(int numberOfRows)
        {

            //Fisher-Yates Shuffle.
            int shuffleSize = (int)Math.Min(Int32.MaxValue, Rows.Count);
            int[] shuffleArray = Enumerable.Range(0, shuffleSize).ToArray();
            Random rand = new Random();
            while (shuffleSize > 1)
            {
                int randomIndex = rand.Next(shuffleSize--);
                int temp = shuffleArray[shuffleSize];
                shuffleArray[shuffleSize] = shuffleArray[randomIndex];
                shuffleArray[randomIndex] = temp;
            }
            PrimitiveDataFrameColumn<long> indices = new PrimitiveDataFrameColumn<long>("Indices", numberOfRows);
            for(long i = 0; i < numberOfRows; i++)
            {
                indices[i] = shuffleArray[i];
            }

            return Clone(indices);
        }
```
What are your thoughts? if this is fine can i create a PR?
I was also going to ask if an Argument exception should be raised if the numberOfRows is greater than Rows.Count?

Kind Regards,
Ramon
