### ISSUE TITLE
TimeZoneInfo should support IANA time zones

### ISSUE THREAD

**Issue by CSurieux** [dotnet/corefxlab#338]
.Net should provide IANA TimeZones to be usable anywhere.

**Comment by mj1856** [comment]
Completely agree, and I'd like to explore this more.

Keep in mind that we already have done this with .Net Core on Linux / OSX, thanks to @eerhardt's excellent work.

For Windows, there are two distinct routes to go.  We could do one or the other, or both.

- Under Windows 8.1 and Windows Server 2012 R2 and greater, there is the `Windows.Globalization.Calendar` API.  This is a WinRT native API that supports IANA-style time zones identifiers. (There are also some data files that back this API that could be read directly, though I'm not certain if there are any guarantees to their format being consistent in future releases.)  If we want to go down this route, it would fit within the scope of [dotnet/coreclr](https://github.com/dotnet/coreclr). It would just be additional platform support into the existing objects.  However, the `GetSystemTimeZones` API would be interesting, as it wouldn't really make sense to return *both* IANA and Windows IDs in the same call.  Either a flag would have to be added, or a different API would have to be exposed.

- The alternative approach to would be to bundle and ship all required data, either as nuget packages or via some other data feed.  This is actually something that could be done within the current APIs, and would work well as a `System.Time` addition.

I'll explore the second option further, as this could perhaps even be done just as an unofficial project.  I'll let others decide about the first option.

CC @tarekgh, as we have discussed this a few times previously.

**Comment by CSurieux** [comment]
Thanks for this explanation, recently I had to integrate Google Calendar API in an OrchardCMS module and I discovered that the mapping IANA / Microsoft is not 1 for 1. This make the deal challenging. 
It seems that there are some solid c# lib doing it. As my problem was very local to eastern Europe, I had to force Paris over Bruxelle, sorry guys in Belgium.....

**Comment by mj1856** [comment]
@CSurieux - Until this is something supported directly, you can use [Noda Time](http://nodatime.org) for the mapping.  See [How to translate between Windows and IANA time zones?](http://stackoverflow.com/q/17348807/634824).

The source of the mappings are [here](http://unicode.org/repos/cldr/trunk/common/supplemental/windowsZones.xml) in the CLDR.

Yes, the mappings are imperfect, but you can get a bit closer if you also know the country code.  In other words, if all you know is `tz = "Romance Standard Time"`, the best mapping is `"Europe/Paris"`.  But, if you know both `tz = "Romance Standard Time"` and `country = "BE"`, then you can map to `"Europe/Brussels"`.

**Comment by mj1856** [comment]
WRT to native support, I did some experimenting and there is good news and bad news.

The good news is that calling the `Windows.Globalization.Calendar` API from .NET is fairly trivial. You set `TargetPlatformVersion>8.1</TargetPlatformVersion>` in the project, add a reference to `Windows`, then you can just use it.

I wrote an extension method as a proof of concept:

```csharp
public static DateTimeOffset ForZone(this DateTimeOffset dto, string timeZoneId)
{
    // Language isn't important here, but calendar and clock are.
    var cal = new Windows.Globalization.Calendar(new [] {"en-US"}, "GregorianCalendar", "24HourClock", timeZoneId);
    cal.SetDateTime(dto);

    // Can't use cal.GetDateTime() because it always uses the local time zone.
    // Instead, get the local time from the calendar properties and use it to calculate the offset manually.
    var dt = new DateTime(cal.Year, cal.Month, cal.Day, cal.Hour, cal.Minute, cal.Second).AddTicks(cal.Nanosecond/100);
    var offset = dt - dto.UtcDateTime;

    return dto.ToOffset(offset);
}
```

And that's the bad news.  From the above you can see how many hoops I had to jump through just to figure out what the correct time zone offset should be.  The magic strings are also a pain.  All of this stems from the need to also use `Windows.Globalization.Calendar` in C++ and JavaScript, as in WinJS.  `GetDateTime()` actually returns a `Windows::Foundation::DateTime` in C#, which just represents a raw timestamp.  In JavaScript is just a `Date` object, and in C# it gets projected to a `DateTimeOffset` but uses the *local* offset always.  There is no property on the `Calendar` class to return the offset, so it has to be calculated from comparing the other properties against the UTC time.

And more bad news - there are no facilities in `Windows.Globalization.Calendar` for exploring the underlying time zone data.  So it's very difficult to determine DST transition points, or to tell if a local time is ambiguous or invalid.  There's also no method that enumerates the available time zones.

In general, I don't have very many good things to say about `Windows.Globalization.Calendar`, and I think it would be very difficult to use it to underpin `TimeZoneInfo`.  So, if native support for IANA time zones were to be added, my recommendation would be to use the underlying data files, rather than going through this API.

**Comment by mj1856** [comment]
Oops - Sorry, didn't mean to close.

**Comment by tarekgh** [comment]
I agree too we need to support IANA natively with the TimeZoneInfo. 

The idea of using WinRT will not be best fit here for different reason:
- WinRT is not support pre Windows 8 
- currently WinRT is not updated that fast yet
- even in Win8+ platforms, there is some server versions not supporting WinRT 

The best solution here is we introduce the TZ provider which can register with TimeZoneInfo class. the provide will provide all needed data (and possibly do some native date/time conversion if we need to). 
To do that we'll need: 
- introduce some new API in TimeZoneInfo to register the provider 
- design the needed APIs in the provider which TimeZoneInfo can call to get the data and possibly do the date/time conversion. 
- people can create their own provider if needed. we can also use Matt's new library to have it implement a provider for IANA support and can be released as NuGet package. 

what you think about this proposal. if you agree please let me know if you are willing to help here and we can do more deeper discussion and talk about the design details.

**Comment by mj1856** [comment]
I like it. :+1:

**Comment by mj1856** [comment]
This is pretty much handled now with my [TimeZoneConverter](https://github.com/mj1856/TimeZoneConverter) library, and is a dup of dotnet/corefx#111897 so I'm closing it here.  Thanks.
