### ISSUE TITLE
Allow constructing of const Utf8CodeUnit & Utf8String literals

### ISSUE THREAD

**Issue by ahsonkhan** [dotnet/corefxlab#361]
Currently Utf8CodeUnit and Utf8String cannot be declared as constants.
- [x] Utf8String literals
- [ ] Utf8CodeUnit literals
- [ ] Push Roslyn about adding const expressions to metadata (at least in custom attributes)

**Comment by krwq** [comment]
In general: Currently Utf8String literals are working although they are not treated as constants and it is not easy to fix because metadata does not support it (unless we do some dirty hacks)
Here is the plan:
Utf8String literals - this is currently supported.
Utf8CodeUnit literals - I haven't came up with the full plan yet. It feels like we should rather have support for few things:
Utf8CodeUnit literals which can be supported are simply ASCII characters (codepoints 0-127). I'm thinking about adding a class for ASCII characters although I don't have a full story figured out yet.
In the end I'd like to convince someone on Roslyn team to help us implement constants in the compiler (and perhaps metadata)
