### ISSUE TITLE
System.CommandLine argument lexing is not aggressive enough in parsing separators

### ISSUE THREAD

**Issue by agocke** [dotnet/corefxlab#402]
Consider the following argument:

```
--arg "C:\Users\andy\somefile"
```

This produces an argument `arg "C` and value `\Users\andy\somefile"` because the argument lexing considers `:` before space. This parsing should be fixed to look for the first instance of _any_ of the legal separators and, once found, split into exactly two substrings, the first being the argument name and the second being the value.

**Comment by alexperovich** [comment]
@agocke Sorry for the delayed response. How did you get an argument like that? The command line `tool --arg "C:\Users\andy\somefile"` will result in 2 arguments: `--arg` and `C:\Users\andy\somefile` which will lex properly.
If you double quote the argument then you can get an argument like that but it isn't supposed to work. The only valid separators for name/value that the lexer parses are `:` and `=` (from https://github.com/dotnet/corefxlab/blob/master/src/System.CommandLine/System/CommandLine/ArgumentLexer.cs#L182). Space is only a valid separator between option and value because the lexer recieves the input as 2 separate arguments.

**Comment by agocke** [comment]
@alexperovich I believe I was trying to pass a command line as an argument to another program, but I don't recall the specific repro. I'll see if I can dig it up somewhere.

**Comment by alexperovich** [comment]
Closing.

The space separation of option and value should be handled by the component that parses the command line string into an argument array. The default handling of `string[] args` in Main methods satisfies this.
