### ISSUE TITLE
Suggestion: additional System.CommandLine generators

### ISSUE THREAD

**Issue by natemcmaster** [dotnet/corefxlab#467]
We have `HelpTextGenerator`.  Why not include generators for other popular formats? Sure would make keeping docs and code aligned much easier.
- Man pages
- Markdown
- HTML
- RST

**Comment by terrajobst** [comment]
I'm not sure we should expose all these formats as I'm not convinced they are used often enough in order to warrant it being part of the core package.

However, I think we should make it possible to write these things on top without having to reimplement all of the the `HelpTextGenerator` class. So the way I'd see this working is that we should expose more of the building blocks that `HelpTextGenerator` uses.

**Comment by alexperovich** [comment]
@natemcmaster Sorry for the delay in responding to this.

I am going to spend some time working on this. I was thinking of having the parser expose a simple object model that contains the commands/options and descriptions. Is there anything specific that would be required to implement these generators?
