### ISSUE TITLE
Channels: Never completing read from SpscUnboundedChannel

### ISSUE THREAD

**Issue by omariom** [dotnet/corefxlab#478]
From what I see in the sources it is possible to have pendingRead1 never be completed. 
```C#
IChannel<int> spscChannel = Channel.Create<int>(Channel.Unbounded, singleReaderWriter: true)

var pendingRead1 = spscChannel.ReadAsync();
var pendingRead2 = spscChannel.ReadAsync();

spscChannel.TryWrite(1);
spscChannel.TryWrite(2);

int firstItem = await pendingRead1 ; // hangs foverver?
```

That's because _blockedReader is being overwritten in ReadAsyncCore.
```C#
private ValueTask<T> ReadAsyncCore(CancellationToken cancellationToken)
{
    lock (SyncObj)
    {
        T item;

        if (TryReadCore(out item))
            return item;

        if (_doneWriting != null)
            return Task.FromException<T>(_doneWriting != s_doneWritingSentinel ? _doneWriting : CreateInvalidCompletionException());

        Reader<T> reader = Reader<T>.Create(cancellationToken);
        _blockedReader = reader;
        return reader.Task;
    }
}

```
Is that an issue at all?

Interesting that WaitToReadAsync explicitly forbids waiting if the previous wait has not been satisfied yet.

**Comment by stephentoub** [comment]
> Is that an issue at all?

You're making multiple calls to ReadAsync that will potentially run concurrently: at that point it's no longer "singleReader" as you've promised by passing true to singleReaderWriter when creating the channel.

The implementation could potentially throw in this case, e.g. adding:
```C#
if (_blockedReader != null)
    throw ...
```
prior to to creating the new reader, but that would merely be to help the developer know they made a mistake, and it wouldn't always detect the mistake, since there's a race condition.

**Comment by omariom** [comment]
>but that would merely be to help the developer know they made a mistake, and it wouldn't always detect the mistake, since there's a race condition

Currently there is a  race  between satisfying the previous read and  deadlock. Throwing will increase the chance to fail earlier -  the previous read will be racing with failure to add next read.
