### ISSUE TITLE
Implement numeric 'R' format 

### ISSUE THREAD

**Issue by KrzysztofCwalina** [dotnet/corefxlab#50]
Repro:
1. Uncomment //GenerateTest(writer, type, 'R', maxPrecision);  in src\System.Text.Formatting\GenerateCompatibilityTests\Program.cs
2. Run the program. It will generate additional format tests
3. Build the formatting library and run the test (run build.cmd from command line)
   Result:
   Some formatting tests will fail.

**Comment by stephenmichaelf** [comment]
@KrzysztofCwalina I am trying to get the tests failing right now. I uncommented the line in Program.cs for the test generator and ran it and got an exception in GenerateNumericTypesTests(). When the StreamWriter is instantiated it uses "..\..\..\tests\NumberFormattingTests.Generated.cs" which doesn't seem to point to the correct folder and throws a DirectoryNotFoundException. 

I looked around and the correct folder seems to be: "corefxlab\tests\System.Text.Formatting.Tests"

Am I misunderstanding how this is supposed to work? This is my first time working in the project. Any help would be appreciated! Thanks!

**Comment by stephenmichaelf** [comment]
So if I change the directories to:

"..\..\..\..\..\tests\System.Text.Formatting.Tests\TimeSpanFormattingTests.Generated.cs"

Then build the project, the files seem to get written to the correct location. Running build produces a ton of output. I checked the code of the PS file and figured out I can run:

![image](https://cloud.githubusercontent.com/assets/450490/20468057/75572b10-af60-11e6-94e2-e58c12d9092f.png)

Then I get several issues as expected with generated methods named *FormatR().

I have two issues:

1. When I open the .xproj for the specific System.Text.Formatting project it opens VS with all the projects open. Is that expected?
2. I am unable to run the System.Text.Formatting.Tests project because it doesn't contain an entry point. What's the best way to do this? I'd let to set a break-point on the tests that are failing and debug them.

Thanks again.

**Comment by stephenmichaelf** [comment]
@davidfowl Could you provide some direction? Thanks!

**Comment by davidfowl** [comment]
Try everything again, we recently fixed some stuff that should make it easier to run tests from within VS (and on the command line).

**Comment by GrabYourPitchforks** [comment]
@KrzysztofCwalina I don't think "R" is a valid format specifier for integral types. Can you clarify what the intent of this test is?

**Comment by KrzysztofCwalina** [comment]
I don't remember the exact context, but I see a comment in the Program.cs file that says // TODO: all of the formats should work.

If we don't think we need R for integral types, then we should change the comment and/or cleanup the Program.cs file as it implies that many of the tests should be enabled in the future.
