### ISSUE TITLE
Why is the attribute called `Primitive`?

### ISSUE THREAD

**Issue by CodesInChaos** [dotnet/corefxlab#518]
https://github.com/dotnet/corefxlab/blob/master/src/System.Slices/src/System/PrimitiveAttribute.cs defines `PrimitiveAttribute` that's used to constrain generic parameters to types that don't contain references.

I don't like the name primitive for that attribute, since that name is used rather inconsistently and doesn't map to [`Type.IsPrimitive`](https://msdn.microsoft.com/en-us/library/system.type.isprimitive.aspx).

Wouldn't the existing [_blittable_](https://msdn.microsoft.com/en-us/library/75dwhxf7.aspx) concept be a better match?

**Comment by KrzysztofCwalina** [comment]
It's unclear whether blitable and this are the same concepts/sets. For example, should char be in the set?

**Comment by CodesInChaos** [comment]
I didn't know that `char` and `bool` aren't blittable. Since at least the former should be supported by `Span`'s reinterpret casting features, calling it blittable wouldn't be a good idea.

I still have doubts about the name *primitive* due to its inconsistent use.

**Comment by KrzysztofCwalina** [comment]
I agree that if the concept is not same as Type.IsPrimitive, we should find a better name for the attribute.

**Comment by mikedn** [comment]
It's not clear what the meaning of this attribute is  (where's that analyzer?) but given the following comment the "primitive" name is definitely wrong:

```C#
/// Casts a Slice of one primitive type (T) to another primitive type (U).
/// These types may not contain managed objects, in order to preserve type
/// safety.  This is checked statically by a Roslyn analyzer.
```

The fact that it says "may not contain managed objects" indicates that these types can be any struct without reference type fields, not just primitive types. I'm not exactly a fan of "blittable" but there aren't many alternatives, "unmanaged" would be only one I have in mind right now. The fact that `char` and `bool` aren't blittable is marshaling specific and since slices are unrelated to marshaling maybe this wouldn't be an issue.

And a bit an off topic observation: this comment is on a method called `Cast` but what that method does isn't a typical cast. Well, it does take a `Span<T>` and produces a `Span<U>` so it resembles a cast but some people may think that it also casts values contained in the span but that isn't true. This method behaves more like C++'s `reinterpret_cast` so a more distinctive name would be preferable.

**Comment by KrzysztofCwalina** [comment]
The T has to be more restricted than "any structs with no references". The exact restriction is: any bit combination represents a valid instance of the type. For example, the following type is not compliant with this restriction:
```C#
public struct ZeroOrOne { 
   public int Value { get; private set; }
   public static ZeroOrOne Zero { return new ZeroOrOne(); }
   public static ZeroOrOne One { return new ZeroOrOne() { Value = 1; }; }
}
```
... as casing Span<int>(new int[] { 2 }) to Span<ZeroOrOne> will result in an instance of ZeroOrOne that has a value 2.

**Comment by mikedn** [comment]
Hmm, that sounds weird. Seeing the analyzer source would perhaps better clarify things.

**Comment by mikedn** [comment]
Maybe you mean something like C++'s POD (plain old data) types? In C#'s case - a struct with no constructors and with only public fields?

**Comment by KrzysztofCwalina** [comment]
Humans will have to apply the attribute and "promise" to be compliant with the restriction. No analyzer will be able to determine this automatically. It will be able to flag a simple mistake of using a non-primitive type as a filed of a primitive type, but not all types with primitive fields are automatically primitive. 

It has little to do with POD. As I said before, *all bit combinations have to represent a valid instance of the type*, and valid is defined as an instance that could be constructed using safe APIs. In the case of ZeroOrOne you cannot create an instance where Value==2 using safe APIs. And so it should not be possible to get such instance either using reinterprt_cast of spans.

**Comment by mikedn** [comment]
Ah, so the analyzer simply checks if the type also has a primitive attribute applied to it, interesting. In other words, I can actually put `[Primitive]` on `ZeroOrOne` and everything will work just fine if I'm OK with `Value` magically becoming 42 or if I have a priori knowledge that the source array only contains 0 and 1.

Sounds good to me but finding a good name for this attribute will be fun :smile:.

**Comment by KrzysztofCwalina** [comment]
Yeah. I would say applying the primitive attribute to ZeroOrOne is a bug, but it will be impossible to write an anayzer to detect such bugs (in all cases).

**Comment by CodesInChaos** [comment]
The rules for converting from a struct to bytes (reinterpret casting `ReadOnlySpan<T>` to `ReadOnlySpan<byte>` or calling `Span.Write<T>`) should probably be more relaxed than the rules for converting the other way.

---

Will future versions of .net still support some kind of sandboxing of verifiable managed code? If yes, there will be additional complications, such as preventing these methods from leaking security critical fields.

**Comment by KrzysztofCwalina** [comment]
they don't need to be more relaxed. All bit combinations form valid byte values.

It's hard to know the future :-) But it's a good issue that we should discuss with security experts. @weshaggard, do we have somebody who could look into this an comment?

**Comment by CodesInChaos** [comment]
Perhaps `Reinterpretable` is a good name.

**Comment by mikedn** [comment]
> Perhaps  Reinterpretable  is a good name.

I'm not 100% convinced about Reinterpretable but it's miles better than Primitive. And in the absence of a better name I think we have a winner.

> All bit combinations form valid byte values.

What about "garbage" bit combinations like padding between fields may contain?

I think that the rules are unnecessarily complex. Or to be more precise, too complex to add value. The only rule that is set in stone is that the types involved in such casts cannot contain references, otherwise memory safety will be compromised. Anything beyond that falls into the category "I hope you know what you are doing" and additional rules will only create another category - "I really hope you know what you are doing".

It's already possible to create a `ZeroOrOne` value where `Value` == 42. You just need to put into another `struct` with explicit layout and overlap it with an `int` field.

**Comment by CodesInChaos** [comment]
> I think that the rules are unnecessarily complex. Or to be more precise, too complex to add value. The only rule that is set in stone is that the types involved in such casts cannot contain references, otherwise memory safety will be compromised.

For fully trusted code I'd tend to agree. If partial trust code is still relevant (not sure about that) and we want these methods to be invokable by untrusted code, things get trickier.

For fully trusted code my biggest concern is actually that it exposes implementation details, turning changes of the field structure into breaking changes.

**Comment by mikedn** [comment]
> If partial trust code is still relevant (not sure about that) and we want these methods to be invokable by untrusted code, things get trickier

It's not in in .NET Core but maybe one day slices will come to the .NET Framework itself. If that were to happen the only way to avoid security issues is probably to put something like `[SecurityCritical]` on the cast method. And security is one reason I asked about garbage padding bits - it turns out that it is possible for sandboxed code to extract information from the stack by using explicit struct layout and a JIT "issue", see https://github.com/dotnet/coreclr/issues/1305.

> For fully trusted code my biggest concern is actually that it exposes implementation details

I think that is what the attribute is actually trying to solve and not the issue of possibly breaking type invariants as in the `ZeroOrOne` case. By requiring this attribute the cast is effectively opt in, you won't be allowed to cast some random third party struct and tinker with its implementation details.

But since the attribute is enforced by a Roslyn analyzer it's all smoke and mirrors anyway. And as mentioned above you can already do this by using explicit struct layout.

**Comment by omariom** [comment]
Slice of structs with references is another case for [ContainsReference](https://github.com/dotnet/coreclr/issues/1135) property ;)
If JIT, NGEN and .NET Native will treat it as a compile time constant then verifications would be no-op for correct types and throw  exception for violators.

**Comment by mikedn** [comment]
> Span of structs with references is another case for ContainsReference property ;)

Actually this is another case of [blittable generic constraint](https://github.com/dotnet/roslyn/issues/3210) ;)

**Comment by omariom** [comment]
Yeah,  we want to be fast being safe )
