### ISSUE TITLE
Which operations on Spans are performance critical?

### ISSUE THREAD

**Issue by omariom** [dotnet/corefxlab#519]
And in which scenarios? May be somebody's tried to use them already and has numbers?

I'd like to work on them. Though, I suspect, it will require (re)writing methods in IL. 

@KrzysztofCwalina @jaredpar @mikedn @VSadov

**Comment by mikedn** [comment]
The indexer I'd assume but there's not much left to do there. I'd try implementing in IL entirely. The existing calls are inlined but due to the way JIT inlines code the result is not as good as it could be, at least in terms of code size. There are other improvements that could be done but they're in the JIT realm, range check elimination for example.

And there are those copy methods which are rather horrible now, see the TODO comments. But I don't think there's much you can do about those without better runtime support.

**Comment by omariom** [comment]
@mikedn 
> I'd try implementing in IL entirely.

Tried  - it only got  worse.

> There are other improvements that could be done but they're in the JIT realm, range check elimination for example.

As I understand it hasn't been decided yet if Slices will get runtime support.  It would be nice if the decision process was more open - Slices (with channels and ref returns/locals), imo, are the most interesting additions to .NET.

**Comment by omariom** [comment]
btw https://github.com/dotnet/corefxlab/pull/525

**Comment by mikedn** [comment]
> As I understand it hasn't been decided yet if Slices will get runtime support.

Maybe you should wait with optimizations until a decision is taken? :smile:

**Comment by omariom** [comment]
I waited long enough )

**Comment by KrzysztofCwalina** [comment]
I think range check elimination would be the first optimization to implement.

**Comment by KrzysztofCwalina** [comment]
And to clarify, I think if we decide to ship this implementation of slicing, we should optimize Span<T> in our back end compilers (e.g. JIT) to be on par with array when it comes to range check elimination.

**Comment by KrzysztofCwalina** [comment]
Also, we could use two scenarios to optimize span: 
1. Utf8String uses span and should be ballpark as perform ant as System.String.
2. Formatting basic primitives (ints, floats, etc) uses Span<T> extensively. I once got most of the formatting code to be on par with CLR's ToString, but since then it regressed a bit when we moved to Span<T> from my previous hacky ByteSpan. ByteSpan was just a pointer + length to memory that does not move (I was using native memory buffers for it).
