### ISSUE TITLE
ManagedBufferPool max buffer size question

### ISSUE THREAD

**Issue by codespare** [dotnet/corefxlab#550]
@sokket [System.Buffers/src/System/Buffers/ManagedBufferPool](https://github.com/dotnet/corefxlab/blob/master/src/System.Buffers/src/System/Buffers/ManagedBufferPool.cs#L32) documents the max buffer size as 2MB (=2 * 2^20 bytes), but the source code value is 2048000 (=2 * 2^10 * 1000 bytes). I was wondering if that is on purpose?

**Comment by sokket** [comment]
@codespare The corefxlab BufferPool is deprecated since the Pool has been added to the BCL here:
https://github.com/dotnet/corefx/blob/master/src/System.Buffers/src/System/Buffers/ArrayPool.cs#L20

Please use that one instead :). The default max buffer there is 1MB instead of 2MB since it was theorized that it would be highly unlikely that an entire webpage with image, css, javascript, and HTML resources would all be contained in the same buffer at the same time.

**Comment by KrzysztofCwalina** [comment]
@sokket, could you remove the old library from corfxlab?

**Comment by codespare** [comment]
I had missed that, thanks!

**Comment by sokket** [comment]
Removing the old Pool with #575
