### ISSUE TITLE
Should the IChannel interface be replaced by a tuple?

### ISSUE THREAD

**Issue by CodesInChaos** [dotnet/corefxlab#578]
The [channels library](https://github.com/dotnet/corefxlab/tree/master/src/System.Threading.Tasks.Channels) contains the `IChannel<...>` interface that combines readable and writable channels.

    public interface IChannel<T> : IChannel<T, T> { }
    public interface IChannel<TInput, TOutput> : IWritableChannel<TInput>, IReadableChannel<TOutput> { }

Are these really a good idea?

I'd rather return a tuple (be it a struct, class or interface) that contains the two unidirectional channels. Something like:

    public struct Channel<TInput, TOutput>
    {
        public IReadableChannel<TOutput> Output { get; }
        public IWritableChannel<TInput> Input { get; }
    }

This properly isolates the two endpoints of a channel so you can hand each side of the communication only the channel they need.

**Comment by i3arnon** [comment]
An `IChannel` doesn't contain two different channels though. It **is** an `IWritableChannel` and an `IReadableChannel` and they aren't necessarily contained in two distinct objects.

Take a simple buffer/queue as an example. It's both `IWritableChannel` and `IReadableChannel` as you can read from it and write to it, but at the end it's just a single data store.

You can still logically hand off only a single "side" by sending an `IChannel` as `IWritableChannel` or `IReadableChannel`.

**Comment by stephentoub** [comment]
I previously experimented with changing the design similar to what's proposed, with something like:
```C#
public abstract class Channel<T> : Channel<T, T> { }

public abstract class Channel<TInput, TOutput>
{
    public abstract ReadableChannel<TOutput> Out { get; }
    public abstract WritableChannel<TInput> In { get; }
}
```
I refactored the library accordingly.  IMO, it made the programming model quite awkward to consume (in part due to the reasons @i3arnon outlines), it made it more difficult to implement custom channels, and it made certain things more expensive (e.g. more objects to construct).  Using abstract base classes had the benefit of being slightly more future proof, but there was enough of a degradation to usage that it really didn't seem worthwhile (there also weren't any obvious perf gains from switching from interface dispatch to virtual dispatch), and I abandoned the effort.
