### ISSUE TITLE
Allow Base64 encoder/decoder to transform in place

### ISSUE THREAD

**Issue by KrzysztofCwalina** [dotnet/corefxlab#786]
Instead of passing different byte buffers for source and destination, there should be an overload that encodes/decodes in-place.

**Comment by KrzysztofCwalina** [comment]
cc @davidfowl

**Comment by davidfowl** [comment]
Very nice!

**Comment by mgravell** [comment]
Decoding should already work correctly if you call `.Decode(foo, foo)`; encoding could be implemented simply by looping backwards rather than forwards, so you don't  over-write data you haven't  read yet. This would also have the advantage of  detecting an invalid length condition immediately rather than eventually.

**Comment by KrzysztofCwalina** [comment]
@mgravell, yeah, decoding is easy and already supported. As to encoding, looping backward is not enough as I don't know the length of the encodes bytes.

**Comment by mgravell** [comment]
Unless I'm being stupid (and I often am), every 3 bytes of input will take 4 bytes of output, with any remainder always rounding up to the next full block of 4 bytes. This should make it perfectly predictable, no?

**Comment by KrzysztofCwalina** [comment]
Ah, I spaced out. I thought this is a thread about the web encoders.

**Comment by mgravell** [comment]
@KrzysztofCwalina actually, no, I'm being stupid. If you are given the same span as source and destination, encode **should** fail, because by definition there isn't enough space guaranteed in that span. But reversing would at least allow decoding a slice over the same larger buffer to work. But then there are other ways of causing off behaviour - offset spans, etc.

**Comment by KrzysztofCwalina** [comment]
submitted #834. I think it works (at least if you have a larger span that what you need to encode).

**Comment by KrzysztofCwalina** [comment]
merged #834
