### ISSUE TITLE
Dispose should ref count rather than lock

### ISSUE THREAD

**Issue by benaadams** [dotnet/corefxlab#922]
Currently Dispose of OwnedMemory throws on Dispose if there are outstanding held references in Reserved Memory.

This should be internalised and all the Disposes though work independently; and the OwnedMemory should be disposed (or returned to pool) when the last one is called.

e.g. the originally issuer shouldn't have to wait for an upstream user to finish before discarding its own reference; its extra unnecessary logic.

Note: Not sure `OnReferenceCountChanged` is then needed in this scenario

**Comment by benaadams** [comment]
@KrzysztofCwalina @davidfowl what is the current use case for the current dispose pattern? (i.e. I might be missing something)

**Comment by KrzysztofCwalina** [comment]
Let's for a moment forget about names. We have two different operations we need to implement (either publicly or privately):
1. OperationA: shuts down the memory object (e.g. returns it to the pool, releases native memory, etc.)
2. OperationB: decrements the refcount. 

OperationA needs to be at least protected virtual, so that subclasses (like the one storing GCHandles) can clean up additional resources. And so I claim that it is exactly what Dispose(bool) is and so it should be called DIspose(bool). 

The semantics of dispose are prescribed in .NET. They are: calls Dispose(true). I think it's ok for dispose to do more than just call Dispose(true), e.g. zero-out some additional fields, but I don't think it is ok for it to not call Dispose(true). 

And so OperationB cannt be Dispose(), as it does not always shut down the object.

**Comment by benaadams** [comment]
Its not greatly safe though, currently you can go
```csharp
var owner = new OwnedArray<byte>(1024);
Memory<byte> memory = owner.Memory;

var res0 = memorySlice.Reserve();
var res1 = memorySlice.Reserve();

var res2 = res0;
res0.Dispose();
res2.Dispose();

owner.Dispose(); // Disposes object, but res1 hasn't been disposed
```

**Comment by benaadams** [comment]
Does https://github.com/dotnet/corefxlab/pull/944 resolved this satisfactorily?

**Comment by KrzysztofCwalina** [comment]
@ahsonkhan, can you triage this issue? I would like to remove all System.Memory issues from corfxlab. thanks.

**Comment by joshfree** [comment]
Closing this old issue now that Span/Memory is in corefx.

/cc @GrabYourPitchforks as FYI on discussion
