### ISSUE TITLE
CommandLine: Allow options specified before the command

### ISSUE THREAD

**Issue by bricelam** [dotnet/corefxlab#927]
I'm using the following definition.

``` C#
syntax.DefineCommand("build", ref command, "Build.");
syntax.DefineOption("verbose", ref verbose, "Show verbose output.");
```

If I invoke the command like this, everything works:

```
$ tool build --verbose
```

However, if I do it like this, it errors.

```
$ tool --verbose build
error: unknown command 'build'
```

**Comment by bricelam** [comment]
Note, you can't allow *parameters* before the command because these would be ambiguous with the command itself.

**Comment by asmichi** [comment]
+1, it would be great if we can define common options which can appear before the command.

I'd like to add one point. We can only allow options common to all commands. Consider the following definition:

```cs
string hash = string.Empty;
syntax.DefineCommand("commit", ref command, Command.Commit, "Commit");
syntax.DefineOption("c", ref hash, true, "Reuse the log message from the specified commit.");

bool count = false;
syntax.DefineCommand("grep", ref command, Command.Grep, "Grep");
syntax.DefineOption("c", ref count, "Show the number of matching lines.");
```

If we allowed options not common to all commands, `tool -c grep commit` would be ambiguous because it could be interpreted as both `tool grep commit -c` ('grep' as a command') and `tool commit -c grep` ('grep' as an argument of `-c`).
