### ISSUE TITLE
Make OwnedMemory<T>.Dispose virtual

### ISSUE THREAD

**Issue by davidfowl** [dotnet/corefxlab#932]
I'd like to implement automatic disposing via ref counting. Today I had to explicitly implement IDisposable to replace the built in behavior:

https://github.com/davidfowl/Channels/blob/fc37daff25a961a3e8f3467582e0f8aca4c1c5d3/src/Channels/ReferenceCountedBuffer.cs#L32

/cc @KrzysztofCwalina

**Comment by KrzysztofCwalina** [comment]
Why don't you override DisposeCore? ... or what would you want to do instead of implementing IDisposable explicitly?

**Comment by KrzysztofCwalina** [comment]
#934 shows how to implement auto-disposable OwnedMemory<T>

**Comment by davidfowl** [comment]
@KrzysztofCwalina Because I want to change the meaning of dispose and not calling the underlying dispose until the ref count is 0

**Comment by KrzysztofCwalina** [comment]
@davidfowl, Dispose (the virtual method on OwnedMeory<T>) needs to have one meaning: shuts down this instance, or decrements the ref count. Subclasses shoudl not change the meaning. This is why I added Release in the sample. Will such Release not work for you?

**Comment by davidfowl** [comment]
I don't ever want to expose a derived class. Callers just call `Dispose()` and it will do the right thing. If I exposed a new API I may as well keep the abstraction I currently have.

**Comment by davidfowl** [comment]
DisposeCore isn't what I want, I overrode that as well and use it to return memory to the pool when the underlying dispose is called

**Comment by KrzysztofCwalina** [comment]
I added Release to the base class.

**Comment by davidfowl** [comment]
Oh no 😄

**Comment by KrzysztofCwalina** [comment]
As I said before, methods on abstractions must have clear semantics. Dispose cannot decrement the ref count in some cases and really dispose (shut down the object) in others. I feel we have a similar problem with Reserve(). It should not make an observable copy in some cases and not others. It's impossible to write code over such abstractions because you never know what the code does.

I know we talked about making ref counting an implementation detail, but I am not sure we can make it work. 

Having said that, I will try to tweak the design a bit; I just need you understand your requirements in more detail, i.e. I need to understand which of you asks are wishes and which are hard requirements.

**Comment by davidfowl** [comment]
@KrzysztofCwalina I changed the code to always call release, the problem is this doesn't always work because as a caller, I need to understand that the backing memory is reference counted because Release will not call dispose automatically for me. If we made that happen with the default implementation, then always calling Release works and I would be ok with that. (Maybe the type shouldn't be disposable)

**Comment by benaadams** [comment]
Should be resolved by #944? with example of [AutoDispose pooling](https://github.com/benaadams/corefxlab/blob/586a813aef60eae9387b49c07b3f485ff296687c/src/System.Buffers.Experimental/System/Buffers/AutoBufferPool.cs)

**Comment by KrzysztofCwalina** [comment]
@ahsonkhan, can you triage this issue? I would like to remove all System.Memory issues from corfxlab. thanks.
